// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StateMachineAndKey.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "StateMachineAndKey.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace StateMachineAndKey {

namespace {

const ::google::protobuf::Descriptor* Bond_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Bond_reflection_ = NULL;
const ::google::protobuf::Descriptor* StateMachine_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StateMachine_reflection_ = NULL;
const ::google::protobuf::Descriptor* StateMachine_Transition_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StateMachine_Transition_reflection_ = NULL;
const ::google::protobuf::Descriptor* StateMachine_TransitionsVector_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StateMachine_TransitionsVector_reflection_ = NULL;
const ::google::protobuf::Descriptor* SecretKey_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SecretKey_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_StateMachineAndKey_2eproto() {
  protobuf_AddDesc_StateMachineAndKey_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "StateMachineAndKey.proto");
  GOOGLE_CHECK(file != NULL);
  Bond_descriptor_ = file->message_type(0);
  static const int Bond_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bond, cm_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bond, c_start1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bond, c_start2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bond, c_end1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bond, c_end2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bond, l_numofcs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bond, c_i_1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bond, c_i_2_),
  };
  Bond_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Bond_descriptor_,
      Bond::default_instance_,
      Bond_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bond, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bond, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Bond));
  StateMachine_descriptor_ = file->message_type(1);
  static const int StateMachine_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine, transitionsvec_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine, virus_),
  };
  StateMachine_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StateMachine_descriptor_,
      StateMachine::default_instance_,
      StateMachine_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(StateMachine));
  StateMachine_Transition_descriptor_ = StateMachine_descriptor_->nested_type(0);
  static const int StateMachine_Transition_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine_Transition, input_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine_Transition, nextstate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine_Transition, isacceptancestate_),
  };
  StateMachine_Transition_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StateMachine_Transition_descriptor_,
      StateMachine_Transition::default_instance_,
      StateMachine_Transition_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine_Transition, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine_Transition, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(StateMachine_Transition));
  StateMachine_TransitionsVector_descriptor_ = StateMachine_descriptor_->nested_type(1);
  static const int StateMachine_TransitionsVector_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine_TransitionsVector, numofstates_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine_TransitionsVector, amountoftransperstate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine_TransitionsVector, trans_),
  };
  StateMachine_TransitionsVector_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StateMachine_TransitionsVector_descriptor_,
      StateMachine_TransitionsVector::default_instance_,
      StateMachine_TransitionsVector_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine_TransitionsVector, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StateMachine_TransitionsVector, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(StateMachine_TransitionsVector));
  SecretKey_descriptor_ = file->message_type(2);
  static const int SecretKey_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecretKey, m_k_t_1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecretKey, m_k_t_2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecretKey, m_k_t_3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecretKey, m_k_for_q_x_1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecretKey, m_k_for_q_x_2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecretKey, m_k_start1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecretKey, m_k_start2_),
  };
  SecretKey_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SecretKey_descriptor_,
      SecretKey::default_instance_,
      SecretKey_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecretKey, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecretKey, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SecretKey));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_StateMachineAndKey_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Bond_descriptor_, &Bond::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StateMachine_descriptor_, &StateMachine::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StateMachine_Transition_descriptor_, &StateMachine_Transition::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StateMachine_TransitionsVector_descriptor_, &StateMachine_TransitionsVector::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SecretKey_descriptor_, &SecretKey::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_StateMachineAndKey_2eproto() {
  delete Bond::default_instance_;
  delete Bond_reflection_;
  delete StateMachine::default_instance_;
  delete StateMachine_reflection_;
  delete StateMachine_Transition::default_instance_;
  delete StateMachine_Transition_reflection_;
  delete StateMachine_TransitionsVector::default_instance_;
  delete StateMachine_TransitionsVector_reflection_;
  delete SecretKey::default_instance_;
  delete SecretKey_reflection_;
}

void protobuf_AddDesc_StateMachineAndKey_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030StateMachineAndKey.proto\022\022StateMachine"
    "AndKey\"\207\001\n\004Bond\022\n\n\002Cm\030\001 \002(\t\022\020\n\010C_start1\030"
    "\002 \002(\t\022\020\n\010C_start2\030\003 \002(\t\022\016\n\006C_end1\030\004 \002(\t\022"
    "\016\n\006C_end2\030\005 \002(\t\022\021\n\tl_numOfCs\030\006 \001(\005\022\r\n\005c_"
    "i_1\030\007 \003(\t\022\r\n\005c_i_2\030\010 \003(\t\"\272\002\n\014StateMachin"
    "e\022J\n\016transitionsVec\030\001 \002(\01322.StateMachine"
    "AndKey.StateMachine.TransitionsVector\022\r\n"
    "\005virus\030\002 \001(\t\032I\n\nTransition\022\r\n\005input\030\001 \002("
    "\t\022\021\n\tnextState\030\002 \002(\005\022\031\n\021IsAcceptanceStat"
    "e\030\003 \002(\010\032\203\001\n\021TransitionsVector\022\023\n\013numOfSt"
    "ates\030\001 \002(\005\022\035\n\025amountOfTransPerState\030\002 \003("
    "\005\022:\n\005trans\030\003 \003(\0132+.StateMachineAndKey.St"
    "ateMachine.Transition\"\224\001\n\tSecretKey\022\017\n\007m"
    "_K_t_1\030\001 \003(\t\022\017\n\007m_K_t_2\030\002 \003(\t\022\017\n\007m_K_t_3"
    "\030\003 \003(\t\022\025\n\rm_K_for_q_x_1\030\004 \003(\t\022\025\n\rm_K_for"
    "_q_x_2\030\005 \003(\t\022\022\n\nm_K_start1\030\006 \002(\t\022\022\n\nm_K_"
    "start2\030\007 \002(\t", 652);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "StateMachineAndKey.proto", &protobuf_RegisterTypes);
  Bond::default_instance_ = new Bond();
  StateMachine::default_instance_ = new StateMachine();
  StateMachine_Transition::default_instance_ = new StateMachine_Transition();
  StateMachine_TransitionsVector::default_instance_ = new StateMachine_TransitionsVector();
  SecretKey::default_instance_ = new SecretKey();
  Bond::default_instance_->InitAsDefaultInstance();
  StateMachine::default_instance_->InitAsDefaultInstance();
  StateMachine_Transition::default_instance_->InitAsDefaultInstance();
  StateMachine_TransitionsVector::default_instance_->InitAsDefaultInstance();
  SecretKey::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_StateMachineAndKey_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_StateMachineAndKey_2eproto {
  StaticDescriptorInitializer_StateMachineAndKey_2eproto() {
    protobuf_AddDesc_StateMachineAndKey_2eproto();
  }
} static_descriptor_initializer_StateMachineAndKey_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Bond::kCmFieldNumber;
const int Bond::kCStart1FieldNumber;
const int Bond::kCStart2FieldNumber;
const int Bond::kCEnd1FieldNumber;
const int Bond::kCEnd2FieldNumber;
const int Bond::kLNumOfCsFieldNumber;
const int Bond::kCI1FieldNumber;
const int Bond::kCI2FieldNumber;
#endif  // !_MSC_VER

Bond::Bond()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Bond::InitAsDefaultInstance() {
}

Bond::Bond(const Bond& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Bond::SharedCtor() {
  _cached_size_ = 0;
  cm_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  c_start1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  c_start2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  c_end1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  c_end2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  l_numofcs_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Bond::~Bond() {
  SharedDtor();
}

void Bond::SharedDtor() {
  if (cm_ != &::google::protobuf::internal::kEmptyString) {
    delete cm_;
  }
  if (c_start1_ != &::google::protobuf::internal::kEmptyString) {
    delete c_start1_;
  }
  if (c_start2_ != &::google::protobuf::internal::kEmptyString) {
    delete c_start2_;
  }
  if (c_end1_ != &::google::protobuf::internal::kEmptyString) {
    delete c_end1_;
  }
  if (c_end2_ != &::google::protobuf::internal::kEmptyString) {
    delete c_end2_;
  }
  if (this != default_instance_) {
  }
}

void Bond::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Bond::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Bond_descriptor_;
}

const Bond& Bond::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_StateMachineAndKey_2eproto();
  return *default_instance_;
}

Bond* Bond::default_instance_ = NULL;

Bond* Bond::New() const {
  return new Bond;
}

void Bond::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_cm()) {
      if (cm_ != &::google::protobuf::internal::kEmptyString) {
        cm_->clear();
      }
    }
    if (has_c_start1()) {
      if (c_start1_ != &::google::protobuf::internal::kEmptyString) {
        c_start1_->clear();
      }
    }
    if (has_c_start2()) {
      if (c_start2_ != &::google::protobuf::internal::kEmptyString) {
        c_start2_->clear();
      }
    }
    if (has_c_end1()) {
      if (c_end1_ != &::google::protobuf::internal::kEmptyString) {
        c_end1_->clear();
      }
    }
    if (has_c_end2()) {
      if (c_end2_ != &::google::protobuf::internal::kEmptyString) {
        c_end2_->clear();
      }
    }
    l_numofcs_ = 0;
  }
  c_i_1_.Clear();
  c_i_2_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Bond::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string Cm = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cm()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->cm().data(), this->cm().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_C_start1;
        break;
      }

      // required string C_start1 = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_C_start1:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_c_start1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->c_start1().data(), this->c_start1().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_C_start2;
        break;
      }

      // required string C_start2 = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_C_start2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_c_start2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->c_start2().data(), this->c_start2().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_C_end1;
        break;
      }

      // required string C_end1 = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_C_end1:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_c_end1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->c_end1().data(), this->c_end1().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_C_end2;
        break;
      }

      // required string C_end2 = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_C_end2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_c_end2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->c_end2().data(), this->c_end2().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_l_numOfCs;
        break;
      }

      // optional int32 l_numOfCs = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_l_numOfCs:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &l_numofcs_)));
          set_has_l_numofcs();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_c_i_1;
        break;
      }

      // repeated string c_i_1 = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_c_i_1:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_c_i_1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->c_i_1(this->c_i_1_size() - 1).data(),
            this->c_i_1(this->c_i_1_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_c_i_1;
        if (input->ExpectTag(66)) goto parse_c_i_2;
        break;
      }

      // repeated string c_i_2 = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_c_i_2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_c_i_2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->c_i_2(this->c_i_2_size() - 1).data(),
            this->c_i_2(this->c_i_2_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(66)) goto parse_c_i_2;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Bond::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string Cm = 1;
  if (has_cm()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->cm().data(), this->cm().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->cm(), output);
  }

  // required string C_start1 = 2;
  if (has_c_start1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->c_start1().data(), this->c_start1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->c_start1(), output);
  }

  // required string C_start2 = 3;
  if (has_c_start2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->c_start2().data(), this->c_start2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->c_start2(), output);
  }

  // required string C_end1 = 4;
  if (has_c_end1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->c_end1().data(), this->c_end1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->c_end1(), output);
  }

  // required string C_end2 = 5;
  if (has_c_end2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->c_end2().data(), this->c_end2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->c_end2(), output);
  }

  // optional int32 l_numOfCs = 6;
  if (has_l_numofcs()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->l_numofcs(), output);
  }

  // repeated string c_i_1 = 7;
  for (int i = 0; i < this->c_i_1_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->c_i_1(i).data(), this->c_i_1(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      7, this->c_i_1(i), output);
  }

  // repeated string c_i_2 = 8;
  for (int i = 0; i < this->c_i_2_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->c_i_2(i).data(), this->c_i_2(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      8, this->c_i_2(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Bond::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string Cm = 1;
  if (has_cm()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->cm().data(), this->cm().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->cm(), target);
  }

  // required string C_start1 = 2;
  if (has_c_start1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->c_start1().data(), this->c_start1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->c_start1(), target);
  }

  // required string C_start2 = 3;
  if (has_c_start2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->c_start2().data(), this->c_start2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->c_start2(), target);
  }

  // required string C_end1 = 4;
  if (has_c_end1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->c_end1().data(), this->c_end1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->c_end1(), target);
  }

  // required string C_end2 = 5;
  if (has_c_end2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->c_end2().data(), this->c_end2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->c_end2(), target);
  }

  // optional int32 l_numOfCs = 6;
  if (has_l_numofcs()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->l_numofcs(), target);
  }

  // repeated string c_i_1 = 7;
  for (int i = 0; i < this->c_i_1_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->c_i_1(i).data(), this->c_i_1(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(7, this->c_i_1(i), target);
  }

  // repeated string c_i_2 = 8;
  for (int i = 0; i < this->c_i_2_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->c_i_2(i).data(), this->c_i_2(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(8, this->c_i_2(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Bond::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string Cm = 1;
    if (has_cm()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->cm());
    }

    // required string C_start1 = 2;
    if (has_c_start1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->c_start1());
    }

    // required string C_start2 = 3;
    if (has_c_start2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->c_start2());
    }

    // required string C_end1 = 4;
    if (has_c_end1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->c_end1());
    }

    // required string C_end2 = 5;
    if (has_c_end2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->c_end2());
    }

    // optional int32 l_numOfCs = 6;
    if (has_l_numofcs()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->l_numofcs());
    }

  }
  // repeated string c_i_1 = 7;
  total_size += 1 * this->c_i_1_size();
  for (int i = 0; i < this->c_i_1_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->c_i_1(i));
  }

  // repeated string c_i_2 = 8;
  total_size += 1 * this->c_i_2_size();
  for (int i = 0; i < this->c_i_2_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->c_i_2(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Bond::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Bond* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Bond*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Bond::MergeFrom(const Bond& from) {
  GOOGLE_CHECK_NE(&from, this);
  c_i_1_.MergeFrom(from.c_i_1_);
  c_i_2_.MergeFrom(from.c_i_2_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cm()) {
      set_cm(from.cm());
    }
    if (from.has_c_start1()) {
      set_c_start1(from.c_start1());
    }
    if (from.has_c_start2()) {
      set_c_start2(from.c_start2());
    }
    if (from.has_c_end1()) {
      set_c_end1(from.c_end1());
    }
    if (from.has_c_end2()) {
      set_c_end2(from.c_end2());
    }
    if (from.has_l_numofcs()) {
      set_l_numofcs(from.l_numofcs());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Bond::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Bond::CopyFrom(const Bond& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Bond::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;

  return true;
}

void Bond::Swap(Bond* other) {
  if (other != this) {
    std::swap(cm_, other->cm_);
    std::swap(c_start1_, other->c_start1_);
    std::swap(c_start2_, other->c_start2_);
    std::swap(c_end1_, other->c_end1_);
    std::swap(c_end2_, other->c_end2_);
    std::swap(l_numofcs_, other->l_numofcs_);
    c_i_1_.Swap(&other->c_i_1_);
    c_i_2_.Swap(&other->c_i_2_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Bond::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Bond_descriptor_;
  metadata.reflection = Bond_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int StateMachine_Transition::kInputFieldNumber;
const int StateMachine_Transition::kNextStateFieldNumber;
const int StateMachine_Transition::kIsAcceptanceStateFieldNumber;
#endif  // !_MSC_VER

StateMachine_Transition::StateMachine_Transition()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void StateMachine_Transition::InitAsDefaultInstance() {
}

StateMachine_Transition::StateMachine_Transition(const StateMachine_Transition& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void StateMachine_Transition::SharedCtor() {
  _cached_size_ = 0;
  input_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  nextstate_ = 0;
  isacceptancestate_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StateMachine_Transition::~StateMachine_Transition() {
  SharedDtor();
}

void StateMachine_Transition::SharedDtor() {
  if (input_ != &::google::protobuf::internal::kEmptyString) {
    delete input_;
  }
  if (this != default_instance_) {
  }
}

void StateMachine_Transition::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StateMachine_Transition::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StateMachine_Transition_descriptor_;
}

const StateMachine_Transition& StateMachine_Transition::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_StateMachineAndKey_2eproto();
  return *default_instance_;
}

StateMachine_Transition* StateMachine_Transition::default_instance_ = NULL;

StateMachine_Transition* StateMachine_Transition::New() const {
  return new StateMachine_Transition;
}

void StateMachine_Transition::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_input()) {
      if (input_ != &::google::protobuf::internal::kEmptyString) {
        input_->clear();
      }
    }
    nextstate_ = 0;
    isacceptancestate_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool StateMachine_Transition::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string input = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_input()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->input().data(), this->input().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_nextState;
        break;
      }

      // required int32 nextState = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_nextState:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nextstate_)));
          set_has_nextstate();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_IsAcceptanceState;
        break;
      }

      // required bool IsAcceptanceState = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_IsAcceptanceState:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isacceptancestate_)));
          set_has_isacceptancestate();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void StateMachine_Transition::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string input = 1;
  if (has_input()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->input().data(), this->input().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->input(), output);
  }

  // required int32 nextState = 2;
  if (has_nextstate()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->nextstate(), output);
  }

  // required bool IsAcceptanceState = 3;
  if (has_isacceptancestate()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->isacceptancestate(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* StateMachine_Transition::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string input = 1;
  if (has_input()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->input().data(), this->input().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->input(), target);
  }

  // required int32 nextState = 2;
  if (has_nextstate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->nextstate(), target);
  }

  // required bool IsAcceptanceState = 3;
  if (has_isacceptancestate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->isacceptancestate(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int StateMachine_Transition::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string input = 1;
    if (has_input()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->input());
    }

    // required int32 nextState = 2;
    if (has_nextstate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->nextstate());
    }

    // required bool IsAcceptanceState = 3;
    if (has_isacceptancestate()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StateMachine_Transition::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const StateMachine_Transition* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const StateMachine_Transition*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void StateMachine_Transition::MergeFrom(const StateMachine_Transition& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_input()) {
      set_input(from.input());
    }
    if (from.has_nextstate()) {
      set_nextstate(from.nextstate());
    }
    if (from.has_isacceptancestate()) {
      set_isacceptancestate(from.isacceptancestate());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void StateMachine_Transition::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StateMachine_Transition::CopyFrom(const StateMachine_Transition& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StateMachine_Transition::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void StateMachine_Transition::Swap(StateMachine_Transition* other) {
  if (other != this) {
    std::swap(input_, other->input_);
    std::swap(nextstate_, other->nextstate_);
    std::swap(isacceptancestate_, other->isacceptancestate_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata StateMachine_Transition::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StateMachine_Transition_descriptor_;
  metadata.reflection = StateMachine_Transition_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int StateMachine_TransitionsVector::kNumOfStatesFieldNumber;
const int StateMachine_TransitionsVector::kAmountOfTransPerStateFieldNumber;
const int StateMachine_TransitionsVector::kTransFieldNumber;
#endif  // !_MSC_VER

StateMachine_TransitionsVector::StateMachine_TransitionsVector()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void StateMachine_TransitionsVector::InitAsDefaultInstance() {
}

StateMachine_TransitionsVector::StateMachine_TransitionsVector(const StateMachine_TransitionsVector& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void StateMachine_TransitionsVector::SharedCtor() {
  _cached_size_ = 0;
  numofstates_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StateMachine_TransitionsVector::~StateMachine_TransitionsVector() {
  SharedDtor();
}

void StateMachine_TransitionsVector::SharedDtor() {
  if (this != default_instance_) {
  }
}

void StateMachine_TransitionsVector::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StateMachine_TransitionsVector::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StateMachine_TransitionsVector_descriptor_;
}

const StateMachine_TransitionsVector& StateMachine_TransitionsVector::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_StateMachineAndKey_2eproto();
  return *default_instance_;
}

StateMachine_TransitionsVector* StateMachine_TransitionsVector::default_instance_ = NULL;

StateMachine_TransitionsVector* StateMachine_TransitionsVector::New() const {
  return new StateMachine_TransitionsVector;
}

void StateMachine_TransitionsVector::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    numofstates_ = 0;
  }
  amountoftransperstate_.Clear();
  trans_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool StateMachine_TransitionsVector::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 numOfStates = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &numofstates_)));
          set_has_numofstates();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_amountOfTransPerState;
        break;
      }

      // repeated int32 amountOfTransPerState = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_amountOfTransPerState:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 16, input, this->mutable_amountoftransperstate())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_amountoftransperstate())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_amountOfTransPerState;
        if (input->ExpectTag(26)) goto parse_trans;
        break;
      }

      // repeated .StateMachineAndKey.StateMachine.Transition trans = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_trans:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_trans()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_trans;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void StateMachine_TransitionsVector::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 numOfStates = 1;
  if (has_numofstates()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->numofstates(), output);
  }

  // repeated int32 amountOfTransPerState = 2;
  for (int i = 0; i < this->amountoftransperstate_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      2, this->amountoftransperstate(i), output);
  }

  // repeated .StateMachineAndKey.StateMachine.Transition trans = 3;
  for (int i = 0; i < this->trans_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->trans(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* StateMachine_TransitionsVector::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 numOfStates = 1;
  if (has_numofstates()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->numofstates(), target);
  }

  // repeated int32 amountOfTransPerState = 2;
  for (int i = 0; i < this->amountoftransperstate_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(2, this->amountoftransperstate(i), target);
  }

  // repeated .StateMachineAndKey.StateMachine.Transition trans = 3;
  for (int i = 0; i < this->trans_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->trans(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int StateMachine_TransitionsVector::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 numOfStates = 1;
    if (has_numofstates()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->numofstates());
    }

  }
  // repeated int32 amountOfTransPerState = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->amountoftransperstate_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->amountoftransperstate(i));
    }
    total_size += 1 * this->amountoftransperstate_size() + data_size;
  }

  // repeated .StateMachineAndKey.StateMachine.Transition trans = 3;
  total_size += 1 * this->trans_size();
  for (int i = 0; i < this->trans_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->trans(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StateMachine_TransitionsVector::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const StateMachine_TransitionsVector* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const StateMachine_TransitionsVector*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void StateMachine_TransitionsVector::MergeFrom(const StateMachine_TransitionsVector& from) {
  GOOGLE_CHECK_NE(&from, this);
  amountoftransperstate_.MergeFrom(from.amountoftransperstate_);
  trans_.MergeFrom(from.trans_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_numofstates()) {
      set_numofstates(from.numofstates());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void StateMachine_TransitionsVector::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StateMachine_TransitionsVector::CopyFrom(const StateMachine_TransitionsVector& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StateMachine_TransitionsVector::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  for (int i = 0; i < trans_size(); i++) {
    if (!this->trans(i).IsInitialized()) return false;
  }
  return true;
}

void StateMachine_TransitionsVector::Swap(StateMachine_TransitionsVector* other) {
  if (other != this) {
    std::swap(numofstates_, other->numofstates_);
    amountoftransperstate_.Swap(&other->amountoftransperstate_);
    trans_.Swap(&other->trans_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata StateMachine_TransitionsVector::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StateMachine_TransitionsVector_descriptor_;
  metadata.reflection = StateMachine_TransitionsVector_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int StateMachine::kTransitionsVecFieldNumber;
const int StateMachine::kVirusFieldNumber;
#endif  // !_MSC_VER

StateMachine::StateMachine()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void StateMachine::InitAsDefaultInstance() {
  transitionsvec_ = const_cast< ::StateMachineAndKey::StateMachine_TransitionsVector*>(&::StateMachineAndKey::StateMachine_TransitionsVector::default_instance());
}

StateMachine::StateMachine(const StateMachine& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void StateMachine::SharedCtor() {
  _cached_size_ = 0;
  transitionsvec_ = NULL;
  virus_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StateMachine::~StateMachine() {
  SharedDtor();
}

void StateMachine::SharedDtor() {
  if (virus_ != &::google::protobuf::internal::kEmptyString) {
    delete virus_;
  }
  if (this != default_instance_) {
    delete transitionsvec_;
  }
}

void StateMachine::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StateMachine::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StateMachine_descriptor_;
}

const StateMachine& StateMachine::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_StateMachineAndKey_2eproto();
  return *default_instance_;
}

StateMachine* StateMachine::default_instance_ = NULL;

StateMachine* StateMachine::New() const {
  return new StateMachine;
}

void StateMachine::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_transitionsvec()) {
      if (transitionsvec_ != NULL) transitionsvec_->::StateMachineAndKey::StateMachine_TransitionsVector::Clear();
    }
    if (has_virus()) {
      if (virus_ != &::google::protobuf::internal::kEmptyString) {
        virus_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool StateMachine::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .StateMachineAndKey.StateMachine.TransitionsVector transitionsVec = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_transitionsvec()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_virus;
        break;
      }

      // optional string virus = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_virus:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_virus()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->virus().data(), this->virus().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void StateMachine::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .StateMachineAndKey.StateMachine.TransitionsVector transitionsVec = 1;
  if (has_transitionsvec()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->transitionsvec(), output);
  }

  // optional string virus = 2;
  if (has_virus()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->virus().data(), this->virus().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->virus(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* StateMachine::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .StateMachineAndKey.StateMachine.TransitionsVector transitionsVec = 1;
  if (has_transitionsvec()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->transitionsvec(), target);
  }

  // optional string virus = 2;
  if (has_virus()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->virus().data(), this->virus().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->virus(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int StateMachine::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .StateMachineAndKey.StateMachine.TransitionsVector transitionsVec = 1;
    if (has_transitionsvec()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->transitionsvec());
    }

    // optional string virus = 2;
    if (has_virus()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->virus());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StateMachine::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const StateMachine* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const StateMachine*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void StateMachine::MergeFrom(const StateMachine& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_transitionsvec()) {
      mutable_transitionsvec()->::StateMachineAndKey::StateMachine_TransitionsVector::MergeFrom(from.transitionsvec());
    }
    if (from.has_virus()) {
      set_virus(from.virus());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void StateMachine::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StateMachine::CopyFrom(const StateMachine& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StateMachine::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_transitionsvec()) {
    if (!this->transitionsvec().IsInitialized()) return false;
  }
  return true;
}

void StateMachine::Swap(StateMachine* other) {
  if (other != this) {
    std::swap(transitionsvec_, other->transitionsvec_);
    std::swap(virus_, other->virus_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata StateMachine::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StateMachine_descriptor_;
  metadata.reflection = StateMachine_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int SecretKey::kMKT1FieldNumber;
const int SecretKey::kMKT2FieldNumber;
const int SecretKey::kMKT3FieldNumber;
const int SecretKey::kMKForQX1FieldNumber;
const int SecretKey::kMKForQX2FieldNumber;
const int SecretKey::kMKStart1FieldNumber;
const int SecretKey::kMKStart2FieldNumber;
#endif  // !_MSC_VER

SecretKey::SecretKey()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SecretKey::InitAsDefaultInstance() {
}

SecretKey::SecretKey(const SecretKey& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SecretKey::SharedCtor() {
  _cached_size_ = 0;
  m_k_start1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  m_k_start2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SecretKey::~SecretKey() {
  SharedDtor();
}

void SecretKey::SharedDtor() {
  if (m_k_start1_ != &::google::protobuf::internal::kEmptyString) {
    delete m_k_start1_;
  }
  if (m_k_start2_ != &::google::protobuf::internal::kEmptyString) {
    delete m_k_start2_;
  }
  if (this != default_instance_) {
  }
}

void SecretKey::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SecretKey::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SecretKey_descriptor_;
}

const SecretKey& SecretKey::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_StateMachineAndKey_2eproto();
  return *default_instance_;
}

SecretKey* SecretKey::default_instance_ = NULL;

SecretKey* SecretKey::New() const {
  return new SecretKey;
}

void SecretKey::Clear() {
  if (_has_bits_[5 / 32] & (0xffu << (5 % 32))) {
    if (has_m_k_start1()) {
      if (m_k_start1_ != &::google::protobuf::internal::kEmptyString) {
        m_k_start1_->clear();
      }
    }
    if (has_m_k_start2()) {
      if (m_k_start2_ != &::google::protobuf::internal::kEmptyString) {
        m_k_start2_->clear();
      }
    }
  }
  m_k_t_1_.Clear();
  m_k_t_2_.Clear();
  m_k_t_3_.Clear();
  m_k_for_q_x_1_.Clear();
  m_k_for_q_x_2_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SecretKey::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string m_K_t_1 = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_m_K_t_1:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_m_k_t_1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->m_k_t_1(this->m_k_t_1_size() - 1).data(),
            this->m_k_t_1(this->m_k_t_1_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_m_K_t_1;
        if (input->ExpectTag(18)) goto parse_m_K_t_2;
        break;
      }

      // repeated string m_K_t_2 = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_m_K_t_2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_m_k_t_2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->m_k_t_2(this->m_k_t_2_size() - 1).data(),
            this->m_k_t_2(this->m_k_t_2_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_m_K_t_2;
        if (input->ExpectTag(26)) goto parse_m_K_t_3;
        break;
      }

      // repeated string m_K_t_3 = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_m_K_t_3:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_m_k_t_3()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->m_k_t_3(this->m_k_t_3_size() - 1).data(),
            this->m_k_t_3(this->m_k_t_3_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_m_K_t_3;
        if (input->ExpectTag(34)) goto parse_m_K_for_q_x_1;
        break;
      }

      // repeated string m_K_for_q_x_1 = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_m_K_for_q_x_1:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_m_k_for_q_x_1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->m_k_for_q_x_1(this->m_k_for_q_x_1_size() - 1).data(),
            this->m_k_for_q_x_1(this->m_k_for_q_x_1_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_m_K_for_q_x_1;
        if (input->ExpectTag(42)) goto parse_m_K_for_q_x_2;
        break;
      }

      // repeated string m_K_for_q_x_2 = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_m_K_for_q_x_2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_m_k_for_q_x_2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->m_k_for_q_x_2(this->m_k_for_q_x_2_size() - 1).data(),
            this->m_k_for_q_x_2(this->m_k_for_q_x_2_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_m_K_for_q_x_2;
        if (input->ExpectTag(50)) goto parse_m_K_start1;
        break;
      }

      // required string m_K_start1 = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_m_K_start1:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_m_k_start1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->m_k_start1().data(), this->m_k_start1().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_m_K_start2;
        break;
      }

      // required string m_K_start2 = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_m_K_start2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_m_k_start2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->m_k_start2().data(), this->m_k_start2().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SecretKey::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated string m_K_t_1 = 1;
  for (int i = 0; i < this->m_k_t_1_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->m_k_t_1(i).data(), this->m_k_t_1(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->m_k_t_1(i), output);
  }

  // repeated string m_K_t_2 = 2;
  for (int i = 0; i < this->m_k_t_2_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->m_k_t_2(i).data(), this->m_k_t_2(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->m_k_t_2(i), output);
  }

  // repeated string m_K_t_3 = 3;
  for (int i = 0; i < this->m_k_t_3_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->m_k_t_3(i).data(), this->m_k_t_3(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->m_k_t_3(i), output);
  }

  // repeated string m_K_for_q_x_1 = 4;
  for (int i = 0; i < this->m_k_for_q_x_1_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->m_k_for_q_x_1(i).data(), this->m_k_for_q_x_1(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->m_k_for_q_x_1(i), output);
  }

  // repeated string m_K_for_q_x_2 = 5;
  for (int i = 0; i < this->m_k_for_q_x_2_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->m_k_for_q_x_2(i).data(), this->m_k_for_q_x_2(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->m_k_for_q_x_2(i), output);
  }

  // required string m_K_start1 = 6;
  if (has_m_k_start1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_k_start1().data(), this->m_k_start1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->m_k_start1(), output);
  }

  // required string m_K_start2 = 7;
  if (has_m_k_start2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_k_start2().data(), this->m_k_start2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      7, this->m_k_start2(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SecretKey::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated string m_K_t_1 = 1;
  for (int i = 0; i < this->m_k_t_1_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_k_t_1(i).data(), this->m_k_t_1(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->m_k_t_1(i), target);
  }

  // repeated string m_K_t_2 = 2;
  for (int i = 0; i < this->m_k_t_2_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_k_t_2(i).data(), this->m_k_t_2(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->m_k_t_2(i), target);
  }

  // repeated string m_K_t_3 = 3;
  for (int i = 0; i < this->m_k_t_3_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_k_t_3(i).data(), this->m_k_t_3(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->m_k_t_3(i), target);
  }

  // repeated string m_K_for_q_x_1 = 4;
  for (int i = 0; i < this->m_k_for_q_x_1_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_k_for_q_x_1(i).data(), this->m_k_for_q_x_1(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->m_k_for_q_x_1(i), target);
  }

  // repeated string m_K_for_q_x_2 = 5;
  for (int i = 0; i < this->m_k_for_q_x_2_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_k_for_q_x_2(i).data(), this->m_k_for_q_x_2(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(5, this->m_k_for_q_x_2(i), target);
  }

  // required string m_K_start1 = 6;
  if (has_m_k_start1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_k_start1().data(), this->m_k_start1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->m_k_start1(), target);
  }

  // required string m_K_start2 = 7;
  if (has_m_k_start2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->m_k_start2().data(), this->m_k_start2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->m_k_start2(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SecretKey::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[5 / 32] & (0xffu << (5 % 32))) {
    // required string m_K_start1 = 6;
    if (has_m_k_start1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->m_k_start1());
    }

    // required string m_K_start2 = 7;
    if (has_m_k_start2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->m_k_start2());
    }

  }
  // repeated string m_K_t_1 = 1;
  total_size += 1 * this->m_k_t_1_size();
  for (int i = 0; i < this->m_k_t_1_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->m_k_t_1(i));
  }

  // repeated string m_K_t_2 = 2;
  total_size += 1 * this->m_k_t_2_size();
  for (int i = 0; i < this->m_k_t_2_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->m_k_t_2(i));
  }

  // repeated string m_K_t_3 = 3;
  total_size += 1 * this->m_k_t_3_size();
  for (int i = 0; i < this->m_k_t_3_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->m_k_t_3(i));
  }

  // repeated string m_K_for_q_x_1 = 4;
  total_size += 1 * this->m_k_for_q_x_1_size();
  for (int i = 0; i < this->m_k_for_q_x_1_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->m_k_for_q_x_1(i));
  }

  // repeated string m_K_for_q_x_2 = 5;
  total_size += 1 * this->m_k_for_q_x_2_size();
  for (int i = 0; i < this->m_k_for_q_x_2_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->m_k_for_q_x_2(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SecretKey::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SecretKey* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SecretKey*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SecretKey::MergeFrom(const SecretKey& from) {
  GOOGLE_CHECK_NE(&from, this);
  m_k_t_1_.MergeFrom(from.m_k_t_1_);
  m_k_t_2_.MergeFrom(from.m_k_t_2_);
  m_k_t_3_.MergeFrom(from.m_k_t_3_);
  m_k_for_q_x_1_.MergeFrom(from.m_k_for_q_x_1_);
  m_k_for_q_x_2_.MergeFrom(from.m_k_for_q_x_2_);
  if (from._has_bits_[5 / 32] & (0xffu << (5 % 32))) {
    if (from.has_m_k_start1()) {
      set_m_k_start1(from.m_k_start1());
    }
    if (from.has_m_k_start2()) {
      set_m_k_start2(from.m_k_start2());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SecretKey::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SecretKey::CopyFrom(const SecretKey& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SecretKey::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000060) != 0x00000060) return false;

  return true;
}

void SecretKey::Swap(SecretKey* other) {
  if (other != this) {
    m_k_t_1_.Swap(&other->m_k_t_1_);
    m_k_t_2_.Swap(&other->m_k_t_2_);
    m_k_t_3_.Swap(&other->m_k_t_3_);
    m_k_for_q_x_1_.Swap(&other->m_k_for_q_x_1_);
    m_k_for_q_x_2_.Swap(&other->m_k_for_q_x_2_);
    std::swap(m_k_start1_, other->m_k_start1_);
    std::swap(m_k_start2_, other->m_k_start2_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SecretKey::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SecretKey_descriptor_;
  metadata.reflection = SecretKey_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace StateMachineAndKey

// @@protoc_insertion_point(global_scope)
