// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StateMachineAndKey.proto

#ifndef PROTOBUF_StateMachineAndKey_2eproto__INCLUDED
#define PROTOBUF_StateMachineAndKey_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace StateMachineAndKey {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_StateMachineAndKey_2eproto();
void protobuf_AssignDesc_StateMachineAndKey_2eproto();
void protobuf_ShutdownFile_StateMachineAndKey_2eproto();

class Bond;
class StateMachine;
class StateMachine_Transition;
class StateMachine_State;
class SecretKey;

// ===================================================================

class Bond : public ::google::protobuf::Message {
 public:
  Bond();
  virtual ~Bond();

  Bond(const Bond& from);

  inline Bond& operator=(const Bond& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Bond& default_instance();

  void Swap(Bond* other);

  // implements Message ----------------------------------------------

  Bond* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Bond& from);
  void MergeFrom(const Bond& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes c_i_1 = 1;
  inline int c_i_1_size() const;
  inline void clear_c_i_1();
  static const int kCI1FieldNumber = 1;
  inline const ::std::string& c_i_1(int index) const;
  inline ::std::string* mutable_c_i_1(int index);
  inline void set_c_i_1(int index, const ::std::string& value);
  inline void set_c_i_1(int index, const char* value);
  inline void set_c_i_1(int index, const void* value, size_t size);
  inline ::std::string* add_c_i_1();
  inline void add_c_i_1(const ::std::string& value);
  inline void add_c_i_1(const char* value);
  inline void add_c_i_1(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& c_i_1() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_c_i_1();

  // repeated bytes c_i_2 = 2;
  inline int c_i_2_size() const;
  inline void clear_c_i_2();
  static const int kCI2FieldNumber = 2;
  inline const ::std::string& c_i_2(int index) const;
  inline ::std::string* mutable_c_i_2(int index);
  inline void set_c_i_2(int index, const ::std::string& value);
  inline void set_c_i_2(int index, const char* value);
  inline void set_c_i_2(int index, const void* value, size_t size);
  inline ::std::string* add_c_i_2();
  inline void add_c_i_2(const ::std::string& value);
  inline void add_c_i_2(const char* value);
  inline void add_c_i_2(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& c_i_2() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_c_i_2();

  // required bytes Cm = 3;
  inline bool has_cm() const;
  inline void clear_cm();
  static const int kCmFieldNumber = 3;
  inline const ::std::string& cm() const;
  inline void set_cm(const ::std::string& value);
  inline void set_cm(const char* value);
  inline void set_cm(const void* value, size_t size);
  inline ::std::string* mutable_cm();
  inline ::std::string* release_cm();
  inline void set_allocated_cm(::std::string* cm);

  // required bytes C_start1 = 4;
  inline bool has_c_start1() const;
  inline void clear_c_start1();
  static const int kCStart1FieldNumber = 4;
  inline const ::std::string& c_start1() const;
  inline void set_c_start1(const ::std::string& value);
  inline void set_c_start1(const char* value);
  inline void set_c_start1(const void* value, size_t size);
  inline ::std::string* mutable_c_start1();
  inline ::std::string* release_c_start1();
  inline void set_allocated_c_start1(::std::string* c_start1);

  // required bytes C_start2 = 5;
  inline bool has_c_start2() const;
  inline void clear_c_start2();
  static const int kCStart2FieldNumber = 5;
  inline const ::std::string& c_start2() const;
  inline void set_c_start2(const ::std::string& value);
  inline void set_c_start2(const char* value);
  inline void set_c_start2(const void* value, size_t size);
  inline ::std::string* mutable_c_start2();
  inline ::std::string* release_c_start2();
  inline void set_allocated_c_start2(::std::string* c_start2);

  // required bytes C_end1 = 6;
  inline bool has_c_end1() const;
  inline void clear_c_end1();
  static const int kCEnd1FieldNumber = 6;
  inline const ::std::string& c_end1() const;
  inline void set_c_end1(const ::std::string& value);
  inline void set_c_end1(const char* value);
  inline void set_c_end1(const void* value, size_t size);
  inline ::std::string* mutable_c_end1();
  inline ::std::string* release_c_end1();
  inline void set_allocated_c_end1(::std::string* c_end1);

  // required bytes C_end2 = 7;
  inline bool has_c_end2() const;
  inline void clear_c_end2();
  static const int kCEnd2FieldNumber = 7;
  inline const ::std::string& c_end2() const;
  inline void set_c_end2(const ::std::string& value);
  inline void set_c_end2(const char* value);
  inline void set_c_end2(const void* value, size_t size);
  inline ::std::string* mutable_c_end2();
  inline ::std::string* release_c_end2();
  inline void set_allocated_c_end2(::std::string* c_end2);

  // optional int32 l_numOfCs = 8;
  inline bool has_l_numofcs() const;
  inline void clear_l_numofcs();
  static const int kLNumOfCsFieldNumber = 8;
  inline ::google::protobuf::int32 l_numofcs() const;
  inline void set_l_numofcs(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:StateMachineAndKey.Bond)
 private:
  inline void set_has_cm();
  inline void clear_has_cm();
  inline void set_has_c_start1();
  inline void clear_has_c_start1();
  inline void set_has_c_start2();
  inline void clear_has_c_start2();
  inline void set_has_c_end1();
  inline void clear_has_c_end1();
  inline void set_has_c_end2();
  inline void clear_has_c_end2();
  inline void set_has_l_numofcs();
  inline void clear_has_l_numofcs();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> c_i_1_;
  ::google::protobuf::RepeatedPtrField< ::std::string> c_i_2_;
  ::std::string* cm_;
  ::std::string* c_start1_;
  ::std::string* c_start2_;
  ::std::string* c_end1_;
  ::std::string* c_end2_;
  ::google::protobuf::int32 l_numofcs_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  friend void  protobuf_AddDesc_StateMachineAndKey_2eproto();
  friend void protobuf_AssignDesc_StateMachineAndKey_2eproto();
  friend void protobuf_ShutdownFile_StateMachineAndKey_2eproto();

  void InitAsDefaultInstance();
  static Bond* default_instance_;
};
// -------------------------------------------------------------------

class StateMachine_Transition : public ::google::protobuf::Message {
 public:
  StateMachine_Transition();
  virtual ~StateMachine_Transition();

  StateMachine_Transition(const StateMachine_Transition& from);

  inline StateMachine_Transition& operator=(const StateMachine_Transition& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StateMachine_Transition& default_instance();

  void Swap(StateMachine_Transition* other);

  // implements Message ----------------------------------------------

  StateMachine_Transition* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StateMachine_Transition& from);
  void MergeFrom(const StateMachine_Transition& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string input = 1;
  inline bool has_input() const;
  inline void clear_input();
  static const int kInputFieldNumber = 1;
  inline const ::std::string& input() const;
  inline void set_input(const ::std::string& value);
  inline void set_input(const char* value);
  inline void set_input(const char* value, size_t size);
  inline ::std::string* mutable_input();
  inline ::std::string* release_input();
  inline void set_allocated_input(::std::string* input);

  // required int32 nextState = 2;
  inline bool has_nextstate() const;
  inline void clear_nextstate();
  static const int kNextStateFieldNumber = 2;
  inline ::google::protobuf::int32 nextstate() const;
  inline void set_nextstate(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:StateMachineAndKey.StateMachine.Transition)
 private:
  inline void set_has_input();
  inline void clear_has_input();
  inline void set_has_nextstate();
  inline void clear_has_nextstate();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* input_;
  ::google::protobuf::int32 nextstate_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_StateMachineAndKey_2eproto();
  friend void protobuf_AssignDesc_StateMachineAndKey_2eproto();
  friend void protobuf_ShutdownFile_StateMachineAndKey_2eproto();

  void InitAsDefaultInstance();
  static StateMachine_Transition* default_instance_;
};
// -------------------------------------------------------------------

class StateMachine_State : public ::google::protobuf::Message {
 public:
  StateMachine_State();
  virtual ~StateMachine_State();

  StateMachine_State(const StateMachine_State& from);

  inline StateMachine_State& operator=(const StateMachine_State& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StateMachine_State& default_instance();

  void Swap(StateMachine_State* other);

  // implements Message ----------------------------------------------

  StateMachine_State* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StateMachine_State& from);
  void MergeFrom(const StateMachine_State& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .StateMachineAndKey.StateMachine.Transition transitionVec = 1;
  inline int transitionvec_size() const;
  inline void clear_transitionvec();
  static const int kTransitionVecFieldNumber = 1;
  inline const ::StateMachineAndKey::StateMachine_Transition& transitionvec(int index) const;
  inline ::StateMachineAndKey::StateMachine_Transition* mutable_transitionvec(int index);
  inline ::StateMachineAndKey::StateMachine_Transition* add_transitionvec();
  inline const ::google::protobuf::RepeatedPtrField< ::StateMachineAndKey::StateMachine_Transition >&
      transitionvec() const;
  inline ::google::protobuf::RepeatedPtrField< ::StateMachineAndKey::StateMachine_Transition >*
      mutable_transitionvec();

  // required bool isAcceptanceState = 2;
  inline bool has_isacceptancestate() const;
  inline void clear_isacceptancestate();
  static const int kIsAcceptanceStateFieldNumber = 2;
  inline bool isacceptancestate() const;
  inline void set_isacceptancestate(bool value);

  // required int32 stateID = 3;
  inline bool has_stateid() const;
  inline void clear_stateid();
  static const int kStateIDFieldNumber = 3;
  inline ::google::protobuf::int32 stateid() const;
  inline void set_stateid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:StateMachineAndKey.StateMachine.State)
 private:
  inline void set_has_isacceptancestate();
  inline void clear_has_isacceptancestate();
  inline void set_has_stateid();
  inline void clear_has_stateid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::StateMachineAndKey::StateMachine_Transition > transitionvec_;
  bool isacceptancestate_;
  ::google::protobuf::int32 stateid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_StateMachineAndKey_2eproto();
  friend void protobuf_AssignDesc_StateMachineAndKey_2eproto();
  friend void protobuf_ShutdownFile_StateMachineAndKey_2eproto();

  void InitAsDefaultInstance();
  static StateMachine_State* default_instance_;
};
// -------------------------------------------------------------------

class StateMachine : public ::google::protobuf::Message {
 public:
  StateMachine();
  virtual ~StateMachine();

  StateMachine(const StateMachine& from);

  inline StateMachine& operator=(const StateMachine& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StateMachine& default_instance();

  void Swap(StateMachine* other);

  // implements Message ----------------------------------------------

  StateMachine* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StateMachine& from);
  void MergeFrom(const StateMachine& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef StateMachine_Transition Transition;
  typedef StateMachine_State State;

  // accessors -------------------------------------------------------

  // repeated .StateMachineAndKey.StateMachine.State StateVec = 1;
  inline int statevec_size() const;
  inline void clear_statevec();
  static const int kStateVecFieldNumber = 1;
  inline const ::StateMachineAndKey::StateMachine_State& statevec(int index) const;
  inline ::StateMachineAndKey::StateMachine_State* mutable_statevec(int index);
  inline ::StateMachineAndKey::StateMachine_State* add_statevec();
  inline const ::google::protobuf::RepeatedPtrField< ::StateMachineAndKey::StateMachine_State >&
      statevec() const;
  inline ::google::protobuf::RepeatedPtrField< ::StateMachineAndKey::StateMachine_State >*
      mutable_statevec();

  // optional string virus = 2;
  inline bool has_virus() const;
  inline void clear_virus();
  static const int kVirusFieldNumber = 2;
  inline const ::std::string& virus() const;
  inline void set_virus(const ::std::string& value);
  inline void set_virus(const char* value);
  inline void set_virus(const char* value, size_t size);
  inline ::std::string* mutable_virus();
  inline ::std::string* release_virus();
  inline void set_allocated_virus(::std::string* virus);

  // @@protoc_insertion_point(class_scope:StateMachineAndKey.StateMachine)
 private:
  inline void set_has_virus();
  inline void clear_has_virus();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::StateMachineAndKey::StateMachine_State > statevec_;
  ::std::string* virus_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_StateMachineAndKey_2eproto();
  friend void protobuf_AssignDesc_StateMachineAndKey_2eproto();
  friend void protobuf_ShutdownFile_StateMachineAndKey_2eproto();

  void InitAsDefaultInstance();
  static StateMachine* default_instance_;
};
// -------------------------------------------------------------------

class SecretKey : public ::google::protobuf::Message {
 public:
  SecretKey();
  virtual ~SecretKey();

  SecretKey(const SecretKey& from);

  inline SecretKey& operator=(const SecretKey& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SecretKey& default_instance();

  void Swap(SecretKey* other);

  // implements Message ----------------------------------------------

  SecretKey* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SecretKey& from);
  void MergeFrom(const SecretKey& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes K_t_1 = 1;
  inline int k_t_1_size() const;
  inline void clear_k_t_1();
  static const int kKT1FieldNumber = 1;
  inline const ::std::string& k_t_1(int index) const;
  inline ::std::string* mutable_k_t_1(int index);
  inline void set_k_t_1(int index, const ::std::string& value);
  inline void set_k_t_1(int index, const char* value);
  inline void set_k_t_1(int index, const void* value, size_t size);
  inline ::std::string* add_k_t_1();
  inline void add_k_t_1(const ::std::string& value);
  inline void add_k_t_1(const char* value);
  inline void add_k_t_1(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& k_t_1() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_k_t_1();

  // repeated bytes K_t_2 = 2;
  inline int k_t_2_size() const;
  inline void clear_k_t_2();
  static const int kKT2FieldNumber = 2;
  inline const ::std::string& k_t_2(int index) const;
  inline ::std::string* mutable_k_t_2(int index);
  inline void set_k_t_2(int index, const ::std::string& value);
  inline void set_k_t_2(int index, const char* value);
  inline void set_k_t_2(int index, const void* value, size_t size);
  inline ::std::string* add_k_t_2();
  inline void add_k_t_2(const ::std::string& value);
  inline void add_k_t_2(const char* value);
  inline void add_k_t_2(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& k_t_2() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_k_t_2();

  // repeated bytes K_t_3 = 3;
  inline int k_t_3_size() const;
  inline void clear_k_t_3();
  static const int kKT3FieldNumber = 3;
  inline const ::std::string& k_t_3(int index) const;
  inline ::std::string* mutable_k_t_3(int index);
  inline void set_k_t_3(int index, const ::std::string& value);
  inline void set_k_t_3(int index, const char* value);
  inline void set_k_t_3(int index, const void* value, size_t size);
  inline ::std::string* add_k_t_3();
  inline void add_k_t_3(const ::std::string& value);
  inline void add_k_t_3(const char* value);
  inline void add_k_t_3(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& k_t_3() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_k_t_3();

  // repeated bytes K_for_q_x_1 = 4;
  inline int k_for_q_x_1_size() const;
  inline void clear_k_for_q_x_1();
  static const int kKForQX1FieldNumber = 4;
  inline const ::std::string& k_for_q_x_1(int index) const;
  inline ::std::string* mutable_k_for_q_x_1(int index);
  inline void set_k_for_q_x_1(int index, const ::std::string& value);
  inline void set_k_for_q_x_1(int index, const char* value);
  inline void set_k_for_q_x_1(int index, const void* value, size_t size);
  inline ::std::string* add_k_for_q_x_1();
  inline void add_k_for_q_x_1(const ::std::string& value);
  inline void add_k_for_q_x_1(const char* value);
  inline void add_k_for_q_x_1(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& k_for_q_x_1() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_k_for_q_x_1();

  // repeated bytes K_for_q_x_2 = 5;
  inline int k_for_q_x_2_size() const;
  inline void clear_k_for_q_x_2();
  static const int kKForQX2FieldNumber = 5;
  inline const ::std::string& k_for_q_x_2(int index) const;
  inline ::std::string* mutable_k_for_q_x_2(int index);
  inline void set_k_for_q_x_2(int index, const ::std::string& value);
  inline void set_k_for_q_x_2(int index, const char* value);
  inline void set_k_for_q_x_2(int index, const void* value, size_t size);
  inline ::std::string* add_k_for_q_x_2();
  inline void add_k_for_q_x_2(const ::std::string& value);
  inline void add_k_for_q_x_2(const char* value);
  inline void add_k_for_q_x_2(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& k_for_q_x_2() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_k_for_q_x_2();

  // required bytes K_start1 = 6;
  inline bool has_k_start1() const;
  inline void clear_k_start1();
  static const int kKStart1FieldNumber = 6;
  inline const ::std::string& k_start1() const;
  inline void set_k_start1(const ::std::string& value);
  inline void set_k_start1(const char* value);
  inline void set_k_start1(const void* value, size_t size);
  inline ::std::string* mutable_k_start1();
  inline ::std::string* release_k_start1();
  inline void set_allocated_k_start1(::std::string* k_start1);

  // required bytes K_start2 = 7;
  inline bool has_k_start2() const;
  inline void clear_k_start2();
  static const int kKStart2FieldNumber = 7;
  inline const ::std::string& k_start2() const;
  inline void set_k_start2(const ::std::string& value);
  inline void set_k_start2(const char* value);
  inline void set_k_start2(const void* value, size_t size);
  inline ::std::string* mutable_k_start2();
  inline ::std::string* release_k_start2();
  inline void set_allocated_k_start2(::std::string* k_start2);

  // @@protoc_insertion_point(class_scope:StateMachineAndKey.SecretKey)
 private:
  inline void set_has_k_start1();
  inline void clear_has_k_start1();
  inline void set_has_k_start2();
  inline void clear_has_k_start2();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> k_t_1_;
  ::google::protobuf::RepeatedPtrField< ::std::string> k_t_2_;
  ::google::protobuf::RepeatedPtrField< ::std::string> k_t_3_;
  ::google::protobuf::RepeatedPtrField< ::std::string> k_for_q_x_1_;
  ::google::protobuf::RepeatedPtrField< ::std::string> k_for_q_x_2_;
  ::std::string* k_start1_;
  ::std::string* k_start2_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_StateMachineAndKey_2eproto();
  friend void protobuf_AssignDesc_StateMachineAndKey_2eproto();
  friend void protobuf_ShutdownFile_StateMachineAndKey_2eproto();

  void InitAsDefaultInstance();
  static SecretKey* default_instance_;
};
// ===================================================================


// ===================================================================

// Bond

// repeated bytes c_i_1 = 1;
inline int Bond::c_i_1_size() const {
  return c_i_1_.size();
}
inline void Bond::clear_c_i_1() {
  c_i_1_.Clear();
}
inline const ::std::string& Bond::c_i_1(int index) const {
  return c_i_1_.Get(index);
}
inline ::std::string* Bond::mutable_c_i_1(int index) {
  return c_i_1_.Mutable(index);
}
inline void Bond::set_c_i_1(int index, const ::std::string& value) {
  c_i_1_.Mutable(index)->assign(value);
}
inline void Bond::set_c_i_1(int index, const char* value) {
  c_i_1_.Mutable(index)->assign(value);
}
inline void Bond::set_c_i_1(int index, const void* value, size_t size) {
  c_i_1_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Bond::add_c_i_1() {
  return c_i_1_.Add();
}
inline void Bond::add_c_i_1(const ::std::string& value) {
  c_i_1_.Add()->assign(value);
}
inline void Bond::add_c_i_1(const char* value) {
  c_i_1_.Add()->assign(value);
}
inline void Bond::add_c_i_1(const void* value, size_t size) {
  c_i_1_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Bond::c_i_1() const {
  return c_i_1_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Bond::mutable_c_i_1() {
  return &c_i_1_;
}

// repeated bytes c_i_2 = 2;
inline int Bond::c_i_2_size() const {
  return c_i_2_.size();
}
inline void Bond::clear_c_i_2() {
  c_i_2_.Clear();
}
inline const ::std::string& Bond::c_i_2(int index) const {
  return c_i_2_.Get(index);
}
inline ::std::string* Bond::mutable_c_i_2(int index) {
  return c_i_2_.Mutable(index);
}
inline void Bond::set_c_i_2(int index, const ::std::string& value) {
  c_i_2_.Mutable(index)->assign(value);
}
inline void Bond::set_c_i_2(int index, const char* value) {
  c_i_2_.Mutable(index)->assign(value);
}
inline void Bond::set_c_i_2(int index, const void* value, size_t size) {
  c_i_2_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Bond::add_c_i_2() {
  return c_i_2_.Add();
}
inline void Bond::add_c_i_2(const ::std::string& value) {
  c_i_2_.Add()->assign(value);
}
inline void Bond::add_c_i_2(const char* value) {
  c_i_2_.Add()->assign(value);
}
inline void Bond::add_c_i_2(const void* value, size_t size) {
  c_i_2_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Bond::c_i_2() const {
  return c_i_2_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Bond::mutable_c_i_2() {
  return &c_i_2_;
}

// required bytes Cm = 3;
inline bool Bond::has_cm() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Bond::set_has_cm() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Bond::clear_has_cm() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Bond::clear_cm() {
  if (cm_ != &::google::protobuf::internal::kEmptyString) {
    cm_->clear();
  }
  clear_has_cm();
}
inline const ::std::string& Bond::cm() const {
  return *cm_;
}
inline void Bond::set_cm(const ::std::string& value) {
  set_has_cm();
  if (cm_ == &::google::protobuf::internal::kEmptyString) {
    cm_ = new ::std::string;
  }
  cm_->assign(value);
}
inline void Bond::set_cm(const char* value) {
  set_has_cm();
  if (cm_ == &::google::protobuf::internal::kEmptyString) {
    cm_ = new ::std::string;
  }
  cm_->assign(value);
}
inline void Bond::set_cm(const void* value, size_t size) {
  set_has_cm();
  if (cm_ == &::google::protobuf::internal::kEmptyString) {
    cm_ = new ::std::string;
  }
  cm_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Bond::mutable_cm() {
  set_has_cm();
  if (cm_ == &::google::protobuf::internal::kEmptyString) {
    cm_ = new ::std::string;
  }
  return cm_;
}
inline ::std::string* Bond::release_cm() {
  clear_has_cm();
  if (cm_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = cm_;
    cm_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Bond::set_allocated_cm(::std::string* cm) {
  if (cm_ != &::google::protobuf::internal::kEmptyString) {
    delete cm_;
  }
  if (cm) {
    set_has_cm();
    cm_ = cm;
  } else {
    clear_has_cm();
    cm_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required bytes C_start1 = 4;
inline bool Bond::has_c_start1() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Bond::set_has_c_start1() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Bond::clear_has_c_start1() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Bond::clear_c_start1() {
  if (c_start1_ != &::google::protobuf::internal::kEmptyString) {
    c_start1_->clear();
  }
  clear_has_c_start1();
}
inline const ::std::string& Bond::c_start1() const {
  return *c_start1_;
}
inline void Bond::set_c_start1(const ::std::string& value) {
  set_has_c_start1();
  if (c_start1_ == &::google::protobuf::internal::kEmptyString) {
    c_start1_ = new ::std::string;
  }
  c_start1_->assign(value);
}
inline void Bond::set_c_start1(const char* value) {
  set_has_c_start1();
  if (c_start1_ == &::google::protobuf::internal::kEmptyString) {
    c_start1_ = new ::std::string;
  }
  c_start1_->assign(value);
}
inline void Bond::set_c_start1(const void* value, size_t size) {
  set_has_c_start1();
  if (c_start1_ == &::google::protobuf::internal::kEmptyString) {
    c_start1_ = new ::std::string;
  }
  c_start1_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Bond::mutable_c_start1() {
  set_has_c_start1();
  if (c_start1_ == &::google::protobuf::internal::kEmptyString) {
    c_start1_ = new ::std::string;
  }
  return c_start1_;
}
inline ::std::string* Bond::release_c_start1() {
  clear_has_c_start1();
  if (c_start1_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = c_start1_;
    c_start1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Bond::set_allocated_c_start1(::std::string* c_start1) {
  if (c_start1_ != &::google::protobuf::internal::kEmptyString) {
    delete c_start1_;
  }
  if (c_start1) {
    set_has_c_start1();
    c_start1_ = c_start1;
  } else {
    clear_has_c_start1();
    c_start1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required bytes C_start2 = 5;
inline bool Bond::has_c_start2() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Bond::set_has_c_start2() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Bond::clear_has_c_start2() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Bond::clear_c_start2() {
  if (c_start2_ != &::google::protobuf::internal::kEmptyString) {
    c_start2_->clear();
  }
  clear_has_c_start2();
}
inline const ::std::string& Bond::c_start2() const {
  return *c_start2_;
}
inline void Bond::set_c_start2(const ::std::string& value) {
  set_has_c_start2();
  if (c_start2_ == &::google::protobuf::internal::kEmptyString) {
    c_start2_ = new ::std::string;
  }
  c_start2_->assign(value);
}
inline void Bond::set_c_start2(const char* value) {
  set_has_c_start2();
  if (c_start2_ == &::google::protobuf::internal::kEmptyString) {
    c_start2_ = new ::std::string;
  }
  c_start2_->assign(value);
}
inline void Bond::set_c_start2(const void* value, size_t size) {
  set_has_c_start2();
  if (c_start2_ == &::google::protobuf::internal::kEmptyString) {
    c_start2_ = new ::std::string;
  }
  c_start2_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Bond::mutable_c_start2() {
  set_has_c_start2();
  if (c_start2_ == &::google::protobuf::internal::kEmptyString) {
    c_start2_ = new ::std::string;
  }
  return c_start2_;
}
inline ::std::string* Bond::release_c_start2() {
  clear_has_c_start2();
  if (c_start2_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = c_start2_;
    c_start2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Bond::set_allocated_c_start2(::std::string* c_start2) {
  if (c_start2_ != &::google::protobuf::internal::kEmptyString) {
    delete c_start2_;
  }
  if (c_start2) {
    set_has_c_start2();
    c_start2_ = c_start2;
  } else {
    clear_has_c_start2();
    c_start2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required bytes C_end1 = 6;
inline bool Bond::has_c_end1() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Bond::set_has_c_end1() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Bond::clear_has_c_end1() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Bond::clear_c_end1() {
  if (c_end1_ != &::google::protobuf::internal::kEmptyString) {
    c_end1_->clear();
  }
  clear_has_c_end1();
}
inline const ::std::string& Bond::c_end1() const {
  return *c_end1_;
}
inline void Bond::set_c_end1(const ::std::string& value) {
  set_has_c_end1();
  if (c_end1_ == &::google::protobuf::internal::kEmptyString) {
    c_end1_ = new ::std::string;
  }
  c_end1_->assign(value);
}
inline void Bond::set_c_end1(const char* value) {
  set_has_c_end1();
  if (c_end1_ == &::google::protobuf::internal::kEmptyString) {
    c_end1_ = new ::std::string;
  }
  c_end1_->assign(value);
}
inline void Bond::set_c_end1(const void* value, size_t size) {
  set_has_c_end1();
  if (c_end1_ == &::google::protobuf::internal::kEmptyString) {
    c_end1_ = new ::std::string;
  }
  c_end1_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Bond::mutable_c_end1() {
  set_has_c_end1();
  if (c_end1_ == &::google::protobuf::internal::kEmptyString) {
    c_end1_ = new ::std::string;
  }
  return c_end1_;
}
inline ::std::string* Bond::release_c_end1() {
  clear_has_c_end1();
  if (c_end1_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = c_end1_;
    c_end1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Bond::set_allocated_c_end1(::std::string* c_end1) {
  if (c_end1_ != &::google::protobuf::internal::kEmptyString) {
    delete c_end1_;
  }
  if (c_end1) {
    set_has_c_end1();
    c_end1_ = c_end1;
  } else {
    clear_has_c_end1();
    c_end1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required bytes C_end2 = 7;
inline bool Bond::has_c_end2() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Bond::set_has_c_end2() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Bond::clear_has_c_end2() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Bond::clear_c_end2() {
  if (c_end2_ != &::google::protobuf::internal::kEmptyString) {
    c_end2_->clear();
  }
  clear_has_c_end2();
}
inline const ::std::string& Bond::c_end2() const {
  return *c_end2_;
}
inline void Bond::set_c_end2(const ::std::string& value) {
  set_has_c_end2();
  if (c_end2_ == &::google::protobuf::internal::kEmptyString) {
    c_end2_ = new ::std::string;
  }
  c_end2_->assign(value);
}
inline void Bond::set_c_end2(const char* value) {
  set_has_c_end2();
  if (c_end2_ == &::google::protobuf::internal::kEmptyString) {
    c_end2_ = new ::std::string;
  }
  c_end2_->assign(value);
}
inline void Bond::set_c_end2(const void* value, size_t size) {
  set_has_c_end2();
  if (c_end2_ == &::google::protobuf::internal::kEmptyString) {
    c_end2_ = new ::std::string;
  }
  c_end2_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Bond::mutable_c_end2() {
  set_has_c_end2();
  if (c_end2_ == &::google::protobuf::internal::kEmptyString) {
    c_end2_ = new ::std::string;
  }
  return c_end2_;
}
inline ::std::string* Bond::release_c_end2() {
  clear_has_c_end2();
  if (c_end2_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = c_end2_;
    c_end2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Bond::set_allocated_c_end2(::std::string* c_end2) {
  if (c_end2_ != &::google::protobuf::internal::kEmptyString) {
    delete c_end2_;
  }
  if (c_end2) {
    set_has_c_end2();
    c_end2_ = c_end2;
  } else {
    clear_has_c_end2();
    c_end2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 l_numOfCs = 8;
inline bool Bond::has_l_numofcs() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Bond::set_has_l_numofcs() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Bond::clear_has_l_numofcs() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Bond::clear_l_numofcs() {
  l_numofcs_ = 0;
  clear_has_l_numofcs();
}
inline ::google::protobuf::int32 Bond::l_numofcs() const {
  return l_numofcs_;
}
inline void Bond::set_l_numofcs(::google::protobuf::int32 value) {
  set_has_l_numofcs();
  l_numofcs_ = value;
}

// -------------------------------------------------------------------

// StateMachine_Transition

// required string input = 1;
inline bool StateMachine_Transition::has_input() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StateMachine_Transition::set_has_input() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StateMachine_Transition::clear_has_input() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StateMachine_Transition::clear_input() {
  if (input_ != &::google::protobuf::internal::kEmptyString) {
    input_->clear();
  }
  clear_has_input();
}
inline const ::std::string& StateMachine_Transition::input() const {
  return *input_;
}
inline void StateMachine_Transition::set_input(const ::std::string& value) {
  set_has_input();
  if (input_ == &::google::protobuf::internal::kEmptyString) {
    input_ = new ::std::string;
  }
  input_->assign(value);
}
inline void StateMachine_Transition::set_input(const char* value) {
  set_has_input();
  if (input_ == &::google::protobuf::internal::kEmptyString) {
    input_ = new ::std::string;
  }
  input_->assign(value);
}
inline void StateMachine_Transition::set_input(const char* value, size_t size) {
  set_has_input();
  if (input_ == &::google::protobuf::internal::kEmptyString) {
    input_ = new ::std::string;
  }
  input_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* StateMachine_Transition::mutable_input() {
  set_has_input();
  if (input_ == &::google::protobuf::internal::kEmptyString) {
    input_ = new ::std::string;
  }
  return input_;
}
inline ::std::string* StateMachine_Transition::release_input() {
  clear_has_input();
  if (input_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = input_;
    input_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void StateMachine_Transition::set_allocated_input(::std::string* input) {
  if (input_ != &::google::protobuf::internal::kEmptyString) {
    delete input_;
  }
  if (input) {
    set_has_input();
    input_ = input;
  } else {
    clear_has_input();
    input_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 nextState = 2;
inline bool StateMachine_Transition::has_nextstate() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StateMachine_Transition::set_has_nextstate() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StateMachine_Transition::clear_has_nextstate() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StateMachine_Transition::clear_nextstate() {
  nextstate_ = 0;
  clear_has_nextstate();
}
inline ::google::protobuf::int32 StateMachine_Transition::nextstate() const {
  return nextstate_;
}
inline void StateMachine_Transition::set_nextstate(::google::protobuf::int32 value) {
  set_has_nextstate();
  nextstate_ = value;
}

// -------------------------------------------------------------------

// StateMachine_State

// repeated .StateMachineAndKey.StateMachine.Transition transitionVec = 1;
inline int StateMachine_State::transitionvec_size() const {
  return transitionvec_.size();
}
inline void StateMachine_State::clear_transitionvec() {
  transitionvec_.Clear();
}
inline const ::StateMachineAndKey::StateMachine_Transition& StateMachine_State::transitionvec(int index) const {
  return transitionvec_.Get(index);
}
inline ::StateMachineAndKey::StateMachine_Transition* StateMachine_State::mutable_transitionvec(int index) {
  return transitionvec_.Mutable(index);
}
inline ::StateMachineAndKey::StateMachine_Transition* StateMachine_State::add_transitionvec() {
  return transitionvec_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::StateMachineAndKey::StateMachine_Transition >&
StateMachine_State::transitionvec() const {
  return transitionvec_;
}
inline ::google::protobuf::RepeatedPtrField< ::StateMachineAndKey::StateMachine_Transition >*
StateMachine_State::mutable_transitionvec() {
  return &transitionvec_;
}

// required bool isAcceptanceState = 2;
inline bool StateMachine_State::has_isacceptancestate() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StateMachine_State::set_has_isacceptancestate() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StateMachine_State::clear_has_isacceptancestate() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StateMachine_State::clear_isacceptancestate() {
  isacceptancestate_ = false;
  clear_has_isacceptancestate();
}
inline bool StateMachine_State::isacceptancestate() const {
  return isacceptancestate_;
}
inline void StateMachine_State::set_isacceptancestate(bool value) {
  set_has_isacceptancestate();
  isacceptancestate_ = value;
}

// required int32 stateID = 3;
inline bool StateMachine_State::has_stateid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void StateMachine_State::set_has_stateid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void StateMachine_State::clear_has_stateid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void StateMachine_State::clear_stateid() {
  stateid_ = 0;
  clear_has_stateid();
}
inline ::google::protobuf::int32 StateMachine_State::stateid() const {
  return stateid_;
}
inline void StateMachine_State::set_stateid(::google::protobuf::int32 value) {
  set_has_stateid();
  stateid_ = value;
}

// -------------------------------------------------------------------

// StateMachine

// repeated .StateMachineAndKey.StateMachine.State StateVec = 1;
inline int StateMachine::statevec_size() const {
  return statevec_.size();
}
inline void StateMachine::clear_statevec() {
  statevec_.Clear();
}
inline const ::StateMachineAndKey::StateMachine_State& StateMachine::statevec(int index) const {
  return statevec_.Get(index);
}
inline ::StateMachineAndKey::StateMachine_State* StateMachine::mutable_statevec(int index) {
  return statevec_.Mutable(index);
}
inline ::StateMachineAndKey::StateMachine_State* StateMachine::add_statevec() {
  return statevec_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::StateMachineAndKey::StateMachine_State >&
StateMachine::statevec() const {
  return statevec_;
}
inline ::google::protobuf::RepeatedPtrField< ::StateMachineAndKey::StateMachine_State >*
StateMachine::mutable_statevec() {
  return &statevec_;
}

// optional string virus = 2;
inline bool StateMachine::has_virus() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StateMachine::set_has_virus() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StateMachine::clear_has_virus() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StateMachine::clear_virus() {
  if (virus_ != &::google::protobuf::internal::kEmptyString) {
    virus_->clear();
  }
  clear_has_virus();
}
inline const ::std::string& StateMachine::virus() const {
  return *virus_;
}
inline void StateMachine::set_virus(const ::std::string& value) {
  set_has_virus();
  if (virus_ == &::google::protobuf::internal::kEmptyString) {
    virus_ = new ::std::string;
  }
  virus_->assign(value);
}
inline void StateMachine::set_virus(const char* value) {
  set_has_virus();
  if (virus_ == &::google::protobuf::internal::kEmptyString) {
    virus_ = new ::std::string;
  }
  virus_->assign(value);
}
inline void StateMachine::set_virus(const char* value, size_t size) {
  set_has_virus();
  if (virus_ == &::google::protobuf::internal::kEmptyString) {
    virus_ = new ::std::string;
  }
  virus_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* StateMachine::mutable_virus() {
  set_has_virus();
  if (virus_ == &::google::protobuf::internal::kEmptyString) {
    virus_ = new ::std::string;
  }
  return virus_;
}
inline ::std::string* StateMachine::release_virus() {
  clear_has_virus();
  if (virus_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = virus_;
    virus_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void StateMachine::set_allocated_virus(::std::string* virus) {
  if (virus_ != &::google::protobuf::internal::kEmptyString) {
    delete virus_;
  }
  if (virus) {
    set_has_virus();
    virus_ = virus;
  } else {
    clear_has_virus();
    virus_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// SecretKey

// repeated bytes K_t_1 = 1;
inline int SecretKey::k_t_1_size() const {
  return k_t_1_.size();
}
inline void SecretKey::clear_k_t_1() {
  k_t_1_.Clear();
}
inline const ::std::string& SecretKey::k_t_1(int index) const {
  return k_t_1_.Get(index);
}
inline ::std::string* SecretKey::mutable_k_t_1(int index) {
  return k_t_1_.Mutable(index);
}
inline void SecretKey::set_k_t_1(int index, const ::std::string& value) {
  k_t_1_.Mutable(index)->assign(value);
}
inline void SecretKey::set_k_t_1(int index, const char* value) {
  k_t_1_.Mutable(index)->assign(value);
}
inline void SecretKey::set_k_t_1(int index, const void* value, size_t size) {
  k_t_1_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SecretKey::add_k_t_1() {
  return k_t_1_.Add();
}
inline void SecretKey::add_k_t_1(const ::std::string& value) {
  k_t_1_.Add()->assign(value);
}
inline void SecretKey::add_k_t_1(const char* value) {
  k_t_1_.Add()->assign(value);
}
inline void SecretKey::add_k_t_1(const void* value, size_t size) {
  k_t_1_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
SecretKey::k_t_1() const {
  return k_t_1_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
SecretKey::mutable_k_t_1() {
  return &k_t_1_;
}

// repeated bytes K_t_2 = 2;
inline int SecretKey::k_t_2_size() const {
  return k_t_2_.size();
}
inline void SecretKey::clear_k_t_2() {
  k_t_2_.Clear();
}
inline const ::std::string& SecretKey::k_t_2(int index) const {
  return k_t_2_.Get(index);
}
inline ::std::string* SecretKey::mutable_k_t_2(int index) {
  return k_t_2_.Mutable(index);
}
inline void SecretKey::set_k_t_2(int index, const ::std::string& value) {
  k_t_2_.Mutable(index)->assign(value);
}
inline void SecretKey::set_k_t_2(int index, const char* value) {
  k_t_2_.Mutable(index)->assign(value);
}
inline void SecretKey::set_k_t_2(int index, const void* value, size_t size) {
  k_t_2_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SecretKey::add_k_t_2() {
  return k_t_2_.Add();
}
inline void SecretKey::add_k_t_2(const ::std::string& value) {
  k_t_2_.Add()->assign(value);
}
inline void SecretKey::add_k_t_2(const char* value) {
  k_t_2_.Add()->assign(value);
}
inline void SecretKey::add_k_t_2(const void* value, size_t size) {
  k_t_2_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
SecretKey::k_t_2() const {
  return k_t_2_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
SecretKey::mutable_k_t_2() {
  return &k_t_2_;
}

// repeated bytes K_t_3 = 3;
inline int SecretKey::k_t_3_size() const {
  return k_t_3_.size();
}
inline void SecretKey::clear_k_t_3() {
  k_t_3_.Clear();
}
inline const ::std::string& SecretKey::k_t_3(int index) const {
  return k_t_3_.Get(index);
}
inline ::std::string* SecretKey::mutable_k_t_3(int index) {
  return k_t_3_.Mutable(index);
}
inline void SecretKey::set_k_t_3(int index, const ::std::string& value) {
  k_t_3_.Mutable(index)->assign(value);
}
inline void SecretKey::set_k_t_3(int index, const char* value) {
  k_t_3_.Mutable(index)->assign(value);
}
inline void SecretKey::set_k_t_3(int index, const void* value, size_t size) {
  k_t_3_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SecretKey::add_k_t_3() {
  return k_t_3_.Add();
}
inline void SecretKey::add_k_t_3(const ::std::string& value) {
  k_t_3_.Add()->assign(value);
}
inline void SecretKey::add_k_t_3(const char* value) {
  k_t_3_.Add()->assign(value);
}
inline void SecretKey::add_k_t_3(const void* value, size_t size) {
  k_t_3_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
SecretKey::k_t_3() const {
  return k_t_3_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
SecretKey::mutable_k_t_3() {
  return &k_t_3_;
}

// repeated bytes K_for_q_x_1 = 4;
inline int SecretKey::k_for_q_x_1_size() const {
  return k_for_q_x_1_.size();
}
inline void SecretKey::clear_k_for_q_x_1() {
  k_for_q_x_1_.Clear();
}
inline const ::std::string& SecretKey::k_for_q_x_1(int index) const {
  return k_for_q_x_1_.Get(index);
}
inline ::std::string* SecretKey::mutable_k_for_q_x_1(int index) {
  return k_for_q_x_1_.Mutable(index);
}
inline void SecretKey::set_k_for_q_x_1(int index, const ::std::string& value) {
  k_for_q_x_1_.Mutable(index)->assign(value);
}
inline void SecretKey::set_k_for_q_x_1(int index, const char* value) {
  k_for_q_x_1_.Mutable(index)->assign(value);
}
inline void SecretKey::set_k_for_q_x_1(int index, const void* value, size_t size) {
  k_for_q_x_1_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SecretKey::add_k_for_q_x_1() {
  return k_for_q_x_1_.Add();
}
inline void SecretKey::add_k_for_q_x_1(const ::std::string& value) {
  k_for_q_x_1_.Add()->assign(value);
}
inline void SecretKey::add_k_for_q_x_1(const char* value) {
  k_for_q_x_1_.Add()->assign(value);
}
inline void SecretKey::add_k_for_q_x_1(const void* value, size_t size) {
  k_for_q_x_1_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
SecretKey::k_for_q_x_1() const {
  return k_for_q_x_1_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
SecretKey::mutable_k_for_q_x_1() {
  return &k_for_q_x_1_;
}

// repeated bytes K_for_q_x_2 = 5;
inline int SecretKey::k_for_q_x_2_size() const {
  return k_for_q_x_2_.size();
}
inline void SecretKey::clear_k_for_q_x_2() {
  k_for_q_x_2_.Clear();
}
inline const ::std::string& SecretKey::k_for_q_x_2(int index) const {
  return k_for_q_x_2_.Get(index);
}
inline ::std::string* SecretKey::mutable_k_for_q_x_2(int index) {
  return k_for_q_x_2_.Mutable(index);
}
inline void SecretKey::set_k_for_q_x_2(int index, const ::std::string& value) {
  k_for_q_x_2_.Mutable(index)->assign(value);
}
inline void SecretKey::set_k_for_q_x_2(int index, const char* value) {
  k_for_q_x_2_.Mutable(index)->assign(value);
}
inline void SecretKey::set_k_for_q_x_2(int index, const void* value, size_t size) {
  k_for_q_x_2_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SecretKey::add_k_for_q_x_2() {
  return k_for_q_x_2_.Add();
}
inline void SecretKey::add_k_for_q_x_2(const ::std::string& value) {
  k_for_q_x_2_.Add()->assign(value);
}
inline void SecretKey::add_k_for_q_x_2(const char* value) {
  k_for_q_x_2_.Add()->assign(value);
}
inline void SecretKey::add_k_for_q_x_2(const void* value, size_t size) {
  k_for_q_x_2_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
SecretKey::k_for_q_x_2() const {
  return k_for_q_x_2_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
SecretKey::mutable_k_for_q_x_2() {
  return &k_for_q_x_2_;
}

// required bytes K_start1 = 6;
inline bool SecretKey::has_k_start1() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SecretKey::set_has_k_start1() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SecretKey::clear_has_k_start1() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SecretKey::clear_k_start1() {
  if (k_start1_ != &::google::protobuf::internal::kEmptyString) {
    k_start1_->clear();
  }
  clear_has_k_start1();
}
inline const ::std::string& SecretKey::k_start1() const {
  return *k_start1_;
}
inline void SecretKey::set_k_start1(const ::std::string& value) {
  set_has_k_start1();
  if (k_start1_ == &::google::protobuf::internal::kEmptyString) {
    k_start1_ = new ::std::string;
  }
  k_start1_->assign(value);
}
inline void SecretKey::set_k_start1(const char* value) {
  set_has_k_start1();
  if (k_start1_ == &::google::protobuf::internal::kEmptyString) {
    k_start1_ = new ::std::string;
  }
  k_start1_->assign(value);
}
inline void SecretKey::set_k_start1(const void* value, size_t size) {
  set_has_k_start1();
  if (k_start1_ == &::google::protobuf::internal::kEmptyString) {
    k_start1_ = new ::std::string;
  }
  k_start1_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SecretKey::mutable_k_start1() {
  set_has_k_start1();
  if (k_start1_ == &::google::protobuf::internal::kEmptyString) {
    k_start1_ = new ::std::string;
  }
  return k_start1_;
}
inline ::std::string* SecretKey::release_k_start1() {
  clear_has_k_start1();
  if (k_start1_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = k_start1_;
    k_start1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SecretKey::set_allocated_k_start1(::std::string* k_start1) {
  if (k_start1_ != &::google::protobuf::internal::kEmptyString) {
    delete k_start1_;
  }
  if (k_start1) {
    set_has_k_start1();
    k_start1_ = k_start1;
  } else {
    clear_has_k_start1();
    k_start1_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required bytes K_start2 = 7;
inline bool SecretKey::has_k_start2() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SecretKey::set_has_k_start2() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SecretKey::clear_has_k_start2() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SecretKey::clear_k_start2() {
  if (k_start2_ != &::google::protobuf::internal::kEmptyString) {
    k_start2_->clear();
  }
  clear_has_k_start2();
}
inline const ::std::string& SecretKey::k_start2() const {
  return *k_start2_;
}
inline void SecretKey::set_k_start2(const ::std::string& value) {
  set_has_k_start2();
  if (k_start2_ == &::google::protobuf::internal::kEmptyString) {
    k_start2_ = new ::std::string;
  }
  k_start2_->assign(value);
}
inline void SecretKey::set_k_start2(const char* value) {
  set_has_k_start2();
  if (k_start2_ == &::google::protobuf::internal::kEmptyString) {
    k_start2_ = new ::std::string;
  }
  k_start2_->assign(value);
}
inline void SecretKey::set_k_start2(const void* value, size_t size) {
  set_has_k_start2();
  if (k_start2_ == &::google::protobuf::internal::kEmptyString) {
    k_start2_ = new ::std::string;
  }
  k_start2_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SecretKey::mutable_k_start2() {
  set_has_k_start2();
  if (k_start2_ == &::google::protobuf::internal::kEmptyString) {
    k_start2_ = new ::std::string;
  }
  return k_start2_;
}
inline ::std::string* SecretKey::release_k_start2() {
  clear_has_k_start2();
  if (k_start2_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = k_start2_;
    k_start2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SecretKey::set_allocated_k_start2(::std::string* k_start2) {
  if (k_start2_ != &::google::protobuf::internal::kEmptyString) {
    delete k_start2_;
  }
  if (k_start2) {
    set_has_k_start2();
    k_start2_ = k_start2;
  } else {
    clear_has_k_start2();
    k_start2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace StateMachineAndKey

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_StateMachineAndKey_2eproto__INCLUDED
